# Sentence-level NER on HIPE-2020 (fr): 

- **NuExtract3** (`numind/NuExtract3`): 4B multilingual structured-extraction model. No native confidence score -- we approximate one from generation token logprobs (see section 3).

Pipeline:

1. Reconstruct sentences from the token-level extraction (`hipe2020_dev_fr_ocrqa.csv`), splitting on the `MISC` `EndOfSentence` flag and respecting `NoSpaceAfter` for detokenization.
2. Run NuExtract3 as a structured-extraction NER: give it a JSON template asking for `{text, label}` entities (PERS/LOC/ORG/TIME/PROD -- matching HIPE's five gold coarse types), and derive an approximate confidence from its generation logprobs.

Caveat on NuExtract3's confidence score: it is **not a calibrated probability**. It approximates "how sure was the decoder about generating exactly this substring", which is a reasonable relative signal (compare confident vs. uncertain extractions from the same model) but should not be treated as a true P(entity is correct) -- unlike GLiNER's score, which comes directly from its classification head.

In [1]:
# Run once per environment (see run_job_cpu.sh / run_job_notebook.sh for the L3iCalcul conda workflow).
# NuExtract3 uses a very recent architecture (Qwen3.5 / "qwen3_5"). If you hit an error like
# "unrecognized model type qwen3_5", upgrade transformers to the latest release, e.g.:
#   pip install -U git+https://github.com/huggingface/transformers.git
!pip install pandas transformers accelerate torch pillow safetensors ipywidgets

Requirement already satisfied: pandas in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (3.0.3)
Requirement already satisfied: transformers in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (5.6.2)
Requirement already satisfied: accelerate in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (1.14.0)
Requirement already satisfied: torch in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (2.12.1)
Requirement already satisfied: pillow in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (12.3.0)
Requirement already satisfied: safetensors in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (0.8.0)
Requirement already satisfied: ipywidgets in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (8.1.8)
Requirement already satisfied: numpy>=1.26.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers) (1.21.0)
Requirement already satisfied: packaging>=20.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers) (2026.6.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers) (0.25.1)
Requirement already satisfied: tqdm>=4.27 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers) (4.68.3)
Requirement already satisfied: click>=8.4.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (3.29.4)
Requirement already satisfied: fsspec>=2023.5.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (0.28.1)
Requirement already satisfied: typing-extensions>=4.1.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers) (4.15.0)
Requirement already satisfied: anyio in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (4.14.1)
Requirement already satisfied: certifi in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (1.0.9)
Requirement already satisfied: idna in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from typer->transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from typer->transformers) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from typer->transformers) (0.0.4)
Requirement already satisfied: psutil in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from accelerate) (7.2.2)
Requirement already satisfied: setuptools<82 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch) (3.1.6)
Requirement already satisfied: cuda-toolkit==13.0.2 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.2)
Requirement already satisfied: nvidia-cublas<=13.1.1.3,>=13.1.0.3 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch) (13.1.1.3)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch) (3.4.5)
Requirement already satisfied: triton==3.7.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch) (3.7.1)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-bindings<14,>=13.0.3->torch) (1.5.6)
Requirement already satisfied: comm>=0.1.3 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipywidgets) (9.15.0)
Requirement already satisfied: traitlets>=4.3.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipywidgets) (5.15.1)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: decorator>=5.1.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.20.0)
Requirement already satisfied: matplotlib-inline>=0.1.6 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.2.2)
Requirement already satisfied: pexpect>4.6 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.8.2)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from jedi>=0.18.2->ipython>=6.1.0->ipywidgets) (0.8.7)
Requirement already satisfied: ptyprocess>=0.5 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from pexpect>4.6->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: six>=1.5 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from rich>=13.8.0->typer->transformers) (4.2.0)
Requirement already satisfied: mdurl~=0.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers) (0.1.2)
Requirement already satisfied: executing>=1.2.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (3.0.1)
Requirement already satisfied: pure-eval in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from stack_data>=0.6.0->ipython>=6.1.0->ipywidgets) (0.2.3)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from jinja2->torch) (3.0.3)

In [2]:
!nvidia-smi

Sun Jul  5 13:37:32 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A40                     On  |   00000000:0B:00.0 Off |                    0 |
|  0%   21C    P8             23W /  300W |       0MiB /  46068MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

In [3]:
import os
os.environ["HF_TOKEN"] = "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"

In [4]:
import json
from typing import Optional

import pandas as pd
import torch
from transformers import AutoModelForImageTextToText, AutoProcessor

## 1. Reconstruct sentences from the token-level extraction

Loads the token table produced by `hipe_ocr_ner_extraction.ipynb`. A sentence ends at the token whose `MISC` contains `EndOfSentence`; a token whose own `MISC` contains `NoSpaceAfter` means no space is inserted before the *next* token. Sentences never cross document boundaries.

In [5]:
CSV_PATH = "hipe2020_dev_fr_ocrqa.csv"
tokens_df = pd.read_csv(CSV_PATH, dtype={"token": str, "MISC": str})
tokens_df["MISC"] = tokens_df["MISC"].fillna("_")
print(tokens_df.shape)
tokens_df.head(3)

(37952, 12)

,document_id,token,NE-COARSE-LIT,MISC,ocr_word_known,entity_type,ocr_ok,entity_span_id,ocr_mean_mention,ocr_ratio_context_5,ocr_ratio_context_10,doc_ocr_mean
0,EXP-1888-08-03-a-i0030,FAITS,O,_,True,O,True,NaN,NaN,1.0,1.0,0.986667
1,EXP-1888-08-03-a-i0030,DIVERS,O,EndOfLine,True,O,True,NaN,NaN,1.0,1.0,0.986667
2,EXP-1888-08-03-a-i0030,La,O,_,True,O,True,NaN,NaN,1.0,1.0,0.986667

In [6]:
def reconstruct_sentences(df: pd.DataFrame) -> pd.DataFrame:
    """Group the token-level HIPE table into sentence-level text, using MISC EndOfSentence /
    NoSpaceAfter flags for detokenization. Returns one row per sentence with the row-index
    range of its tokens in `df`, so results can be joined back to per-token OCR/NER features."""
    sentences = []
    doc_id = None
    sent_idx = 0
    pieces: list[str] = []
    no_space_before_next = False
    row_start = None

    for i, row in df.iterrows():
        if row["document_id"] != doc_id:
            # New document: HIPE documents always end on an EndOfSentence token in practice,
            # so there should be no leftover buffer here.
            doc_id = row["document_id"]
            sent_idx = 0
            pieces = []
            no_space_before_next = False
            row_start = i

        if pieces and not no_space_before_next:
            pieces.append(" ")
        pieces.append(str(row["token"]))
        no_space_before_next = "NoSpaceAfter" in row["MISC"]

        if "EndOfSentence" in row["MISC"]:
            sentences.append(
                {
                    "document_id": doc_id,
                    "sentence_id": sent_idx,
                    "sentence_text": "".join(pieces),
                    "row_start": row_start,
                    "row_end": i,
                }
            )
            sent_idx += 1
            pieces = []
            no_space_before_next = False
            row_start = i + 1

    return pd.DataFrame(sentences)


sentences_df = reconstruct_sentences(tokens_df)
print(sentences_df.shape[0], "sentences across", sentences_df["document_id"].nunique(), "documents")
sentences_df.head(5)

1244 sentences across 43 documents

,document_id,sentence_id,sentence_text,row_start,row_end
0,EXP-1888-08-03-a-i0030,0,FAITS DIVERS La panique des éléphants au grand...,0,11
1,EXP-1888-08-03-a-i0030,1,"— Quatre dromadaires et huit éléphants, fourni...",12,51
2,EXP-1888-08-03-a-i0030,2,Les éléphants étaient enchaînés à la nuque ot ...,52,68
3,EXP-1888-08-03-a-i0030,3,Tout à coup les éléphants furent effrayés par ...,69,95
4,EXP-1888-08-03-a-i0030,4,"Six d'entre eux rompirent leurs chaînes, et, m...",96,130

## 2. Load NuExtract3

4B parameter vision-language model used here in text-only mode. In bf16 this needs a real GPU (fine on `gpu-a40`/`gpu-a6000`/`gpu-h100`; likely too tight on `gpu-2080ti`'s 11GB once activations are added).

In [7]:
!pip install numind torchvision flash-linear-attention[cuda]

Requirement already satisfied: numind in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (0.3.0)
Requirement already satisfied: torchvision in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (0.27.1)
Requirement already satisfied: flash-linear-attention[cuda] in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (0.5.1)
Requirement already satisfied: aiohttp-retry>=2.8.3 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from numind) (2.9.1)
Requirement already satisfied: aiohttp>=3.8.4 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from numind) (3.14.1)
Requirement already satisfied: jsonschema in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from numind) (4.26.0)
Requirement already satisfied: orjson in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from numind) (3.11.9)
Requirement already satisfied: pydantic>=2.11 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from numind) (2.13.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from numind) (2.9.0.post0)
Requirement already satisfied: typing-extensions>=4.7.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from numind) (4.15.0)
Requirement already satisfied: urllib3 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from numind) (2.7.0)
Requirement already satisfied: numpy in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torchvision) (2.4.6)
Requirement already satisfied: torch==2.12.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torchvision) (2.12.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torchvision) (12.3.0)
Requirement already satisfied: filelock in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (3.29.4)
Requirement already satisfied: setuptools<82 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (3.6.1)
Requirement already satisfied: jinja2 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (2026.6.0)
Requirement already satisfied: cuda-toolkit==13.0.2 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.1->torchvision) (13.0.2)
Requirement already satisfied: nvidia-cublas<=13.1.1.3,>=13.1.0.3 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (13.1.1.3)
Requirement already satisfied: cuda-bindings<14,>=13.0.3 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (13.3.1)
Requirement already satisfied: nvidia-cudnn-cu13==9.20.0.48 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (9.20.0.48)
Requirement already satisfied: nvidia-cusparselt-cu13==0.8.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (0.8.1)
Requirement already satisfied: nvidia-nccl-cu13==2.29.7 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (2.29.7)
Requirement already satisfied: nvidia-nvshmem-cu13==3.4.5 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (3.4.5)
Requirement already satisfied: triton==3.7.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from torch==2.12.1->torchvision) (3.7.1)
Requirement already satisfied: nvidia-cuda-runtime==13.0.96.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.1->torchvision) (13.0.96)
Requirement already satisfied: nvidia-cufft==12.0.0.61.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.1->torchvision) (12.0.0.61)
Requirement already satisfied: nvidia-cufile==1.15.1.6.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.1->torchvision) (1.15.1.6)
Requirement already satisfied: nvidia-cuda-cupti==13.0.85.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.1->torchvision) (13.0.85)
Requirement already satisfied: nvidia-curand==10.4.0.35.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.1->torchvision) (10.4.0.35)
Requirement already satisfied: nvidia-cusolver==12.0.4.66.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.1->torchvision) (12.0.4.66)
Requirement already satisfied: nvidia-cusparse==12.6.3.3.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.1->torchvision) (12.6.3.3)
Requirement already satisfied: nvidia-nvjitlink==13.0.88.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.1->torchvision) (13.0.88)
Requirement already satisfied: nvidia-cuda-nvrtc==13.0.88.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.1->torchvision) (13.0.88)
Requirement already satisfied: nvidia-nvtx==13.0.85.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-toolkit[cudart,cufft,cufile,cupti,curand,cusolver,cusparse,nvjitlink,nvrtc,nvtx]==13.0.2; platform_system == "Linux"->torch==2.12.1->torchvision) (13.0.85)
Requirement already satisfied: cuda-pathfinder>=1.4.2 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from cuda-bindings<14,>=13.0.3->torch==2.12.1->torchvision) (1.5.6)
Requirement already satisfied: fla-core==0.5.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from flash-linear-attention[cuda]) (0.5.1)
Requirement already satisfied: transformers>=4.45.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from flash-linear-attention[cuda]) (5.6.2)
Requirement already satisfied: einops in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from fla-core==0.5.1->flash-linear-attention[cuda]) (0.8.2)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from aiohttp>=3.8.4->numind) (2.7.1)
Requirement already satisfied: aiosignal>=1.4.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from aiohttp>=3.8.4->numind) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from aiohttp>=3.8.4->numind) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from aiohttp>=3.8.4->numind) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from aiohttp>=3.8.4->numind) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from aiohttp>=3.8.4->numind) (0.5.2)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from aiohttp>=3.8.4->numind) (1.24.2)
Requirement already satisfied: idna>=2.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from yarl<2.0,>=1.17.0->aiohttp>=3.8.4->numind) (3.18)
Requirement already satisfied: annotated-types>=0.6.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from pydantic>=2.11->numind) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from pydantic>=2.11->numind) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from pydantic>=2.11->numind) (0.4.2)
Requirement already satisfied: six>=1.5 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from python-dateutil>=2.8.2->numind) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from sympy>=1.13.3->torch==2.12.1->torchvision) (1.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.5.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers>=4.45.0->flash-linear-attention[cuda]) (1.21.0)
Requirement already satisfied: packaging>=20.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers>=4.45.0->flash-linear-attention[cuda]) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers>=4.45.0->flash-linear-attention[cuda]) (6.0.3)
Requirement already satisfied: regex>=2025.10.22 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers>=4.45.0->flash-linear-attention[cuda]) (2026.6.28)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers>=4.45.0->flash-linear-attention[cuda]) (0.22.2)
Requirement already satisfied: typer in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers>=4.45.0->flash-linear-attention[cuda]) (0.25.1)
Requirement already satisfied: safetensors>=0.4.3 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers>=4.45.0->flash-linear-attention[cuda]) (0.8.0)
Requirement already satisfied: tqdm>=4.27 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from transformers>=4.45.0->flash-linear-attention[cuda]) (4.68.3)
Requirement already satisfied: click>=8.4.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention[cuda]) (8.4.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention[cuda]) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention[cuda]) (0.28.1)
Requirement already satisfied: anyio in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention[cuda]) (4.14.1)
Requirement already satisfied: certifi in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention[cuda]) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention[cuda]) (1.0.9)
Requirement already satisfied: h11>=0.16 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.5.0->transformers>=4.45.0->flash-linear-attention[cuda]) (0.16.0)
Requirement already satisfied: shellingham>=1.3.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from typer->transformers>=4.45.0->flash-linear-attention[cuda]) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from typer->transformers>=4.45.0->flash-linear-attention[cuda]) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from typer->transformers>=4.45.0->flash-linear-attention[cuda]) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from rich>=13.8.0->typer->transformers>=4.45.0->flash-linear-attention[cuda]) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from rich>=13.8.0->typer->transformers>=4.45.0->flash-linear-attention[cuda]) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers>=4.45.0->flash-linear-attention[cuda]) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from jinja2->torch==2.12.1->torchvision) (3.0.3)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from jsonschema->numind) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from jsonschema->numind) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in /Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages (from jsonschema->numind) (2026.6.3)

In [8]:
MODEL_ID = "numind/NuExtract3"

processor = AutoProcessor.from_pretrained(MODEL_ID, trust_remote_code=True)
model = AutoModelForImageTextToText.from_pretrained(
    MODEL_ID,
    dtype=torch.bfloat16,
    device_map="auto",
    trust_remote_code=True,
).eval()

/Utilisateurs/pchau/.conda/envs/notebook/lib/python3.11/site-packages/torch/cuda/__init__.py:187: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 12040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at /pytorch/c10/cuda/CUDAFunctions.cpp:119.)
  return torch._C._cuda_getDeviceCount() > 0
[transformers] The fast path is not available because one of the required library is not installed. Falling back to torch implementation. To install follow https://github.com/fla-org/flash-linear-attention#installation and https://github.com/Dao-AILab/causal-conv1d

Loading weights:   0%|          | 0/723 [00:00<?, ?it/s]

## 3. NER via structured extraction, with an approximate per-entity confidence

Template asks for a flat list of `{text, label}` entities. `text` is `verbatim-string` (must appear literally in the input) which is what lets us locate it in the raw generated output to compute a confidence score.

In [9]:
NER_TEMPLATE = {
    "entities": [
        {
            "text": "verbatim-string",
            "label": ["PERS", "LOC", "ORG", "TIME", "PROD"],
        }
    ]
}

NER_INSTRUCTIONS = (
    "Extract all named entities mentioned in the text, verbatim. "
    "PERS = person names. LOC = places, cities, countries, geographic locations. "
    "ORG = organizations, companies, institutions. "
    "TIME = dates, time expressions, or named historical periods/events tied to a specific time. "
    "PROD = named products or named works (books, ships, etc.). "
    "Do not invent entities that are not literally present in the text."
)


def extract_json_from_output(raw_output: str) -> dict:
    """NuExtract can wrap output in ```json ... ``` code fences; strip them if present."""
    text = raw_output.strip()
    if text.startswith("```"):
        text = text.strip("`")
        if text.startswith("json"):
            text = text[len("json"):]
    return json.loads(text.strip())


def run_ner_with_confidence(
    sentence: str,
    template: dict = NER_TEMPLATE,
    instructions: str = NER_INSTRUCTIONS,
    max_new_tokens: int = 512,
) -> tuple[list[dict], str]:
    """Run NuExtract3 NER on one sentence. Returns (entities, raw_model_output) where each
    entity dict has text/label/confidence. confidence is the mean per-token generation
    probability over the characters of that entity's `text` value in the raw output
    (None if the value could not be located, e.g. the model didn't return valid JSON)."""
    messages = [
        {
            "role": "user",
            "content": [{"type": "text", "text": sentence}],
        }
    ]

    inputs = processor.apply_chat_template(
        messages,
        add_generation_prompt=True,
        tokenize=True,
        return_dict=True,
        return_tensors="pt",
        template=json.dumps(template),
        instructions=instructions,
        enable_thinking=False,
    ).to(model.device)

    with torch.inference_mode():
        out = model.generate(
            **inputs,
            max_new_tokens=max_new_tokens,
            do_sample=False,
            output_scores=True,
            return_dict_in_generate=True,
        )

    gen_ids = out.sequences[0, inputs.input_ids.shape[1]:]
    step_scores = out.scores  # tuple of (1, vocab) logits, one per generated step

    # Per-generated-token probability of the token that was actually chosen (greedy decoding).
    token_probs = []
    for step_logits, tok_id in zip(step_scores, gen_ids):
        prob = torch.softmax(step_logits[0], dim=-1)[tok_id].item()
        token_probs.append(prob)

    # Incrementally decode to get the character span each generated token contributes,
    # so we can later average token_probs over an entity's character range.
    token_spans = []
    text_so_far = ""
    for i in range(len(gen_ids)):
        new_text = processor.tokenizer.decode(
            gen_ids[: i + 1], skip_special_tokens=True, clean_up_tokenization_spaces=False
        )
        token_spans.append((len(text_so_far), len(new_text)))
        text_so_far = new_text

    raw_output = text_so_far

    try:
        parsed = extract_json_from_output(raw_output)
        raw_entities = parsed.get("entities", [])
    except (json.JSONDecodeError, AttributeError):
        return [], raw_output

    entities = []
    search_cursor = 0
    for ent in raw_entities:
        ent_text = str(ent.get("text", ""))
        ent_label = ent.get("label")

        idx = raw_output.find(ent_text, search_cursor) if ent_text else -1
        confidence = None
        if idx != -1:
            span_start, span_end = idx, idx + len(ent_text)
            search_cursor = span_end
            overlapping = [
                p for (s, e), p in zip(token_spans, token_probs) if e > span_start and s < span_end
            ]
            if overlapping:
                confidence = sum(overlapping) / len(overlapping)

        entities.append({"text": ent_text, "label": ent_label, "confidence": confidence})

    return entities, raw_output

### Example: run on a single sentence first

In [10]:
import time

example_sentence = sentences_df.iloc[0]["sentence_text"]
print("Input sentence:", example_sentence)

start = time.time()
example_entities, example_raw_output = run_ner_with_confidence(example_sentence)
elapsed = time.time() - start
print(f"\Time: {elapsed:.1f}s")
print("\nRaw model output:\n", example_raw_output)
print("\nParsed entities with confidence:")
for e in example_entities:
    print(e)

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

Input sentence: FAITS DIVERS La panique des éléphants au grand cortège dc Munich.
\Time: 153.9s

Raw model output:
 {"entities": [{"text": "Munich", "label": "LOC"}]}


Parsed entities with confidence:
{'text': 'Munich', 'label': 'LOC', 'confidence': 0.8847107092539469}

## 4. Apply to all sentences

One `generate()` call per sentence -- this is the expensive part (a 4B model, sequentially, over ~thousands of sentences). Run this on an L3iCalcul GPU node via `sbatch` rather than interactively for the full dataset. Checkpoints to CSV every `CHECKPOINT_EVERY` sentences so a killed/timed-out job doesn't lose progress -- rerun the cell and it resumes from the checkpoint.

In [ ]:
from pathlib import Path

RESULTS_PATH = Path("hipe2020_dev_fr_nuextract3_ner.csv")
CHECKPOINT_EVERY = 50

if RESULTS_PATH.exists():
    done_df = pd.read_csv(RESULTS_PATH)
    done_sentence_keys = set(zip(done_df["document_id"], done_df["sentence_id"]))
    results = done_df.to_dict("records")
else:
    done_sentence_keys = set()
    results = []

for n_processed, (_, srow) in enumerate(sentences_df.iterrows(), start=1):
    key = (srow["document_id"], srow["sentence_id"])
    if key in done_sentence_keys:
        continue

    entities, _ = run_ner_with_confidence(srow["sentence_text"])
    if not entities:
        results.append(
            {
                "document_id": srow["document_id"],
                "sentence_id": srow["sentence_id"],
                "sentence_text": srow["sentence_text"],
                "entity_text": None,
                "entity_label": None,
                "confidence": None,
            }
        )
    else:
        for e in entities:
            results.append(
                {
                    "document_id": srow["document_id"],
                    "sentence_id": srow["sentence_id"],
                    "sentence_text": srow["sentence_text"],
                    "entity_text": e["text"],
                    "entity_label": e["label"],
                    "confidence": e["confidence"],
                }
            )

    if n_processed % CHECKPOINT_EVERY == 0:
        pd.DataFrame(results).to_csv(RESULTS_PATH, index=False)
        print(f"Checkpoint: {n_processed}/{len(sentences_df)} sentences processed")

pd.DataFrame(results).to_csv(RESULTS_PATH, index=False)
print("Done. Saved to", RESULTS_PATH)

[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.
[transformers] Setting `pad_token_id` to `eos_token_id`:248044 for open-end generation.

In [ ]:
ner_results_df = pd.read_csv(RESULTS_PATH)
print(ner_results_df.shape)
ner_results_df.head(20)